language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r operations/requirements.txt
# command to run tests
script:
  - pytest operations/test # or py.test for Python versions 3.5 and below
